language: c
dist: bionic
os:
  - linux
compiler:
  - clang
  - gcc
arch:
  - amd64
  - arm64
  - ppc64le
env:
  global:
    - MAKEFLAGS="-j 2"
matrix:
  include:
    - os: linux
      compiler: gcc
      arch: amd64
      env: BUILD_ARCH="x86" # Only do the gcc x86 build to reduce clutter
    # Default xcode image
    - os: linux
      compiler: gcc
      arch: ppc64le
    - os: linux
      compiler: clang 
      arch: ppc64le
    - os: osx
      compiler: clang # Workaround travis setting CC=["clang", "gcc"]
      arch: amd64
    # Latest xcode image (needs periodic updating)
    - os: osx
      compiler: clang
      osx_image: xcode11.2
      arch: amd64
  exclude:
    - os: osx
      compiler: gcc

install:
  - ci/travis-install.sh

script:
  - ci/travis-build.sh
